### ISSUE TITLE
Incorrect plan file size limits & legacy plans

### ISSUE THREAD

**Issue by PadreZippo** [sketchfab/blender-plugin#100]
- The Premium plan is incorrectly set to a limit of 200 MB instead of 500 MB
- The Plus and Business plans no longer exist, so they don't need to be there

https://github.com/sketchfab/blender-plugin/blob/ed43e6c2329ce3034d62ac065d6c52f48ae23f93/addons/io_sketchfab_plugin/__init__.py#L170-L177

**Comment by Mach1Studio** [comment]
Ok, thanks, will give it a try
