### ISSUE TITLE
 Error when exporting model

### ISSUE THREAD

**Issue by Mach1Studio** [sketchfab/blender-plugin#103]
Hi, I'm trying to export a model to my Organization profile. I get this error.

![image](https://user-images.githubusercontent.com/100152536/223475405-d43177c3-cce9-4c40-9079-7e37dfcd49df.png)

Not sure what to check for, if there is a fix on my end.

thx.

Marc.

**Comment by PadreZippo** [comment]
This seems to be somewhat related to https://github.com/sketchfab/blender-plugin/issues/100

https://github.com/sketchfab/blender-plugin/blob/ed43e6c2329ce3034d62ac065d6c52f48ae23f93/addons/io_sketchfab_plugin/__init__.py#L170-L177

**Comment by PadreZippo** [comment]
We shipped a new version (1.6.0) of the Blender plugin, which will fix this issue: https://github.com/sketchfab/blender-plugin/releases

And, regarding Blender 4.0, this will fix the **_importer_**, as well as a couple other small bugs, but we have not yet updated the processing on our backend to handle Blender 4.0 .blend files, so the **_exporter_** feature still won't work yet. If you need to export, we recommend staying on 3.6.1 LTS or manually exporting GLB files until we update our processing for Blender 4.0 .blend files.
