### ISSUE TITLE
Can I log in with my google account?

### ISSUE THREAD

**Issue by rejuvenator** [sketchfab/blender-plugin#11]
I log into the Sketchfab with my google account. Is there a way for me to log in inside the plugin?

**Comment by loicSketchfab** [comment]
Hello @rejuvenator !

If you log in Sketchfab with your Google account, the e-mail + password combination to use to log inside the plugin should be the same.

In other words, the credentials used to login into the addon are the same than on the website.

Let us know if this doesn't work for you (with any useful information such as your sketchfab profile name, e-mail, version of blender, OS, as well as blender console output if there is one).
If you don't want your info to be public (who would?), you can of course create a ticket on [Sketchfab Help Center](https://help.sketchfab.com/hc/en-us/requests/new).

Hope this can help !

**Comment by adhhrg** [comment]
same here cant log in with google, so I deleted my google sketch fab account and tried to create a new account. but it says my email is already used, then I clicked forget password, didn't receive any email. so I'm stuck cant even create an account.

**Comment by will-ca** [comment]
@loicSketchfab 

The entire point of logging into Sketchfab with a Google account is that *we don't have a password* that we use on the Sketchfab website.

(Instead, the Sketchfab website does a bunch permissions-requesting authentication and authorization stuff with Google servers. This takes the form of a bunch of OAUTH tokens behind the scenes, but shows to us end users as a big button that says "Log in with Google".

We click the button, then click "Ok", and we're logged in. There's no password, and there isn't really even an explicitly provided e-mail either, other than the one implicitly tied to our Google account.)

In the past, we were able to log in to the Blender plugin using a Sketchfab API key IIRC. In fact, when I go to the "Password" section of my account settings, it's implied that this still works as the preferred way to log in to exporter addons:

---

![image](https://user-images.githubusercontent.com/37680486/79520259-d9005d80-8045-11ea-98a4-19eedf2ea09d.png)

---

It evidently doesn't though.

**Comment by will-ca** [comment]
@rejuvenator @adhhrg 

I managed to create a password for my account by logging out, then resetting the password for my e-mail from the login screen.

**Comment by rmanky** [comment]
> @rejuvenator @adhhrg
> 
> I managed to create a password for my account by logging out, then resetting the password for my e-mail from the login screen.
> 
> AFAICT, I can still log in by Google as long I don't dissociate it in my account settings.
> 
> This is kind of an ugly workaround though, especially given it's undocumented.

This works! Thank you

**Comment by takiyao** [comment]
I have the same problem and the workaround of resetting the password is not possible for me due to security reasons. Could we please have another way to log in or to authenticate our account?

**Comment by melMass** [comment]
Hi,

I'm facing the same issue. I created my account by using Google, so password-less. 
Trying to set a password on Sketchfab doesn't work as it asks for an old password that does not exist.
Can't we use the API key to log in with the addon?

Thanks

**Comment by PadreZippo** [comment]
You can now authenticate the plugin using your API Token instead of email + password for cases when you use a third-party identity provider such as Google.

![image](https://github.com/sketchfab/blender-plugin/assets/7097291/4925856a-67a6-4370-9e77-ff59295c20c6)

You can find your API Token here: https://sketchfab.com/settings/password
