### ISSUE TITLE
Not working on blender 3.6.1

### ISSUE THREAD

**Issue by soykhaler** [sketchfab/blender-plugin#110]
only importing empty objects
![image](https://github.com/sketchfab/blender-plugin/assets/74861088/7a110516-d341-4e0e-a65c-f0731055026b)

**Comment by PadreZippo** [comment]
Hi there,

I could not reproduce the issue; I was able to import a model successfully in Blender 3.6.1

<img width="1728" alt="image" src="https://github.com/sketchfab/blender-plugin/assets/7097291/8092aff9-76c0-442c-aa1f-3764bf8dc03f">

Do you see that behavior with every model?

**Comment by soykhaler** [comment]
fixed, was my blender version
