### ISSUE TITLE
sketchfab not working blender 4.0

### ISSUE THREAD

**Issue by sajensaju** [sketchfab/blender-plugin#117]

**Comment by FlipBliss** [comment]
Same issue. imports nothing to scene in 4.0

**Comment by bahadirsonmez59** [comment]
Same issue. imports nothing to scene in 4.0.1

**Comment by kezie101** [comment]
Same Issue. Says something about a KeyError: '4c8................61'

**Comment by 4Bakers** [comment]
I remember reading that there were breaking changes in the Python API for mesh alteration or smth, so I figured this would happen

**Comment by PadreZippo** [comment]
We shipped a new version (1.6.0) of the Blender plugin: https://github.com/sketchfab/blender-plugin/releases

This will fix the **_importer_**, as well as a couple other small bugs, but we have not yet updated the processing on our backend to handle Blender 4.0 .blend files, so the **_exporter_** feature still won't work yet.
