### ISSUE TITLE
object cant will see

### ISSUE THREAD

**Issue by abhinav3423** [sketchfab/blender-plugin#119]

**Comment by ojkarrr** [comment]
When importing objects are not seen. This is happening to me from the Blender 4.0 version

**Comment by PadreZippo** [comment]
We shipped a new version (1.6.0) of the Blender plugin: https://github.com/sketchfab/blender-plugin/releases

This will fix the **_importer_**, as well as a couple other small bugs, but we have not yet updated the processing on our backend to handle Blender 4.0 .blend files, so the **_exporter_** feature still won't work yet.
