### ISSUE TITLE
1.6.1 Missing subfolder in install ZIP

### ISSUE THREAD

**Issue by maymaymoto** [sketchfab/blender-plugin#124]
Previous versions have a subfolder within the ZIP file. Version 1.6.1 is missing this subfolder. The add-on installs without an error in Blender, but does not initialize. I was able to get the add-on to work by adding a subfolder "sketchfab-plugin-1-6-1" in the ZIP file and then installing it in Blender.

**Comment by PadreZippo** [comment]
Hi there,

Thanks for the report. The folder structure / content of the ZIPs in 1.6.0 and 1.6.1 look identical to me and there is no subfolder. However, I do reproduce the issue that v1.6.0 installs correctly while v1.6.1 does not.

![image](https://github.com/sketchfab/blender-plugin/assets/7097291/2c8293ab-1af2-4874-8bee-eb7533c7b021)

**Comment by PadreZippo** [comment]
Looks like you were right, thanks for the report. We updated the [1.6.1 zip file](https://github.com/sketchfab/blender-plugin/releases/download/1.6.1/sketchfab-plugin-1-6-1.zip).

It's weird that macOS unzips them in an identical way though... 🤷
