### ISSUE TITLE
Cannot find my purchased model :(

### ISSUE THREAD

**Issue by mmerlangeRA** [sketchfab/blender-plugin#13]
Hello, 
I purchased a 3d model under mmerlange@gmail.com
https://sketchfab.com/3d-models/toon-dinosaur-tyrannosaurus-rex-e10d88f382974d34b21d9da8db60ff19
I installed the Blender plugin, connected and no way I can find my model : many others but not mine :(
Thanks for your help

**Comment by loicSketchfab** [comment]
Hi @mmerlangeRA :wave: 

Although this might come a little bit late for your model, we've finally added the possibility to search through your purchased models from the add-on (might come in handy in the future..).

You should be able to use this by installing the [latest version of the add-on](https://github.com/sketchfab/blender-plugin/releases/tag/1.3.0) (you'll have to select "Store purchases" from the appropriate dropdown).
![image](https://user-images.githubusercontent.com/52042414/102910475-ed211800-447a-11eb-91dd-6dbba32f6d02.png)


I'm closing this ticket for now, but do not hesitate to let us know if something does not seem to work for you.
