### ISSUE TITLE
No Search Results 

### ISSUE THREAD

**Issue by DanishCh29** [sketchfab/blender-plugin#136]
I am getting no search results in this addon in Both Blender 4.0 and 4.1, Please help. I tried reinstalling, re-logging and it still won't work.
![Screenshot (126)](https://github.com/sketchfab/blender-plugin/assets/157707497/680c21a8-1dd8-4f9e-910f-7ae034c96a05)

**Comment by KHyoushin** [comment]
I'm having the same problem, I don't know what to do with it...

**Comment by PadreZippo** [comment]
Sorry about that. We had a cache issue affecting performance and search results across the website and APIs/plugins. It should be resolved now.
