### ISSUE TITLE
not working with 4.2 update

### ISSUE THREAD

**Issue by AbinVarghexe** [sketchfab/blender-plugin#138]

**Comment by MrHyplex9511** [comment]
I have a fix for the above. You see if its giving error like fix line 1409 of innit.py. then go to that line and replace the EEVEE with EEVEE_NEXT.

And if it is giving error fix line 1393, then

            bpy.context.scene.render.engine = "BLENDER_EEVEE" <---------- Change BLENDER_EEVEE to BLENDER_EEVEE_NEXT

**Comment by golumbi** [comment]
hi i did that still doesnt import anything. i also zipped with this code remove everything , but doesnt work . i have no crash messages or anything.
