### ISSUE TITLE
Importing a model switches render engine to Eevee

### ISSUE THREAD

**Issue by AdityaGupta1** [sketchfab/blender-plugin#14]
I use Cycles for my renders, but whenever I import a model, it switches the render engine to Eevee. Is there an option to turn this off or is it a bug?

**Comment by PadreZippo** [comment]
I suspect this is the intended behavior, as Eevee allows the closest match between Sketchfab's and Blender's PBR channels, but I will let @loicSketchfab confirm.

**Comment by llriu** [comment]
From my experience, the materials work fine in Cycles. It's annoying to have to switch back to cycles every time I import a model.

**Comment by loicSketchfab** [comment]
👋 
We've included a fix for this issue in version [1.5.0](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) of the addon, to keep either Cycles or Eevee as a render engine upon import.
Closing this issue, but feel free to reopen if something is off for your usecase 👍

**Comment by AdityaGupta1** [comment]
Seems to work perfectly now. Thank you very much!
