### ISSUE TITLE
Importing does not work on linux

### ISSUE THREAD

**Issue by donalshortt** [sketchfab/blender-plugin#151]
Neither importing via URL or from the model browser works. I get the following error:

Python: Traceback (most recent call last):
  File "/home/donal/.config/blender/4.2/scripts/addons/sketchfab-plugin-1-6-1/__init__.py", line 1393, in modal
    bpy.context.scene.render.engine = "BLENDER_EEVEE"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: enum "BLENDER_EEVEE" not found in ('BLENDER_EEVEE_NEXT', 'BLENDER_WORKBENCH', 'CYCLES')

Using version 1.6.1
Using blender 4.2.1

**Comment by xseejx-linux** [comment]
Hello,
I had the same issue and to resolve it I edited the init.py file, by searching for the line:
`bpy.context.scene.render.engine = "BLENDER_EEVEE"`

and changed it from **BLENDER_EEVEE** to **BLENDER_EEVEE_NEXT**, it should looks like this:
`bpy.context.scene.render.engine = "BLENDER_EEVEE_NEXT"`

Once I saved the file, I restarted Blender, and the Import button started working.

**Comment by donalshortt** [comment]
this worked.

thank you!
