### ISSUE TITLE
NormalMap Is Connecting To Alpha socket

### ISSUE THREAD

**Issue by lichtwerk** [sketchfab/blender-plugin#16]
Hi there,

was handling a bugreport over on developer.blender.org (https://developer.blender.org/T82213), but since we dont maintain this Addon, I am reporting this here.

So the issue is that since a change on the blender side, see ( https://developer.blender.org/rBb248ec97769fa654a3ee8bb2a643046b79e7c030 ) the NormalMap Is Connecting To Alpha socket.

The sketchfab Addon has not been updated to to accomodate [it uses socket indices -- these changed -- instead of names]
https://github.com/sketchfab/blender-plugin/blob/master/addons/io_sketchfab_plugin/blender/imp/gltf2_blender_map_normal.py#L88
See also https://developer.blender.org/D8965
(Have not checked if other sockets are affected as well)

Thx in advance!

**Comment by loicSketchfab** [comment]
Thanks for the very detailled and explained report @lichtwerk , that'll make it easier for us to fix.
We'll try to update this soon :+1:

**Comment by loicSketchfab** [comment]
Hi @lichtwerk :wave: 

Sorry if this comes up a little late, but if you hadn't fixed it already, we've fixed this behaviour in the latest release: 
https://github.com/sketchfab/blender-plugin/releases/tag/1.3.0

I'm closing this one, thanks for your report !
