### ISSUE TITLE
No login option/fields using latest Blender Alpha and Betas

### ISSUE THREAD

**Issue by elecinfec** [sketchfab/blender-plugin#34]
![sketchfab addon login bug](https://user-images.githubusercontent.com/7127487/115692861-a88d8680-a35f-11eb-82f8-461f7cb61837.png)

There are just no login input fields. 

Thanks.

**Comment by GouthamPPanicker** [comment]
same for me

**Comment by hhzx** [comment]
me too

**Comment by mwstandsfor** [comment]
Running 2.93 LTS and having the same issue

**Comment by PadreZippo** [comment]
Hi everyone, thanks for your patience. Indeed, this should be solved by version 1.4.0 of the plugin: https://github.com/sketchfab/blender-plugin/releases/latest
