### ISSUE TITLE
Paste model URL directly into plugin

### ISSUE THREAD

**Issue by takosuke** [sketchfab/blender-plugin#35]
I prefer browsing for models through the website, it would be nice to just paste the model url or id into the search box (or elsewhere) and find it directly. As it stands, I have to repeat the search once I've found what I want in the website and hope to find it in the thumbnails.

**Comment by loicSketchfab** [comment]
We've added such a feature with the [release 1.5.0](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) of the addon, feel free to try it out, and re-open the issue if something does not work as expected.
