### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by hgntrung** [sketchfab/blender-plugin#36]
I'm using Blender portable. Software located at desktop belongs to C Drivers
My Admin account name is HoangTrung. However, the addon keeps asking for permission from the  Admin folder.

Is there any that I can fix this issue?

Thank you
![Issue](https://user-images.githubusercontent.com/69626770/118391274-a7e5c880-b65d-11eb-8f07-bfc4cc1ce385.PNG)

**Comment by loicSketchfab** [comment]
Hey @hgntrung .

I'm not 100% sure what happens in your case.

However, here are a few thoughts to try to help you:

* Do you run Blender as Administrator ? The part of the plugin where you experience a crash is when we try to create a temporary directory. By default, this directory should be created at a location where the Windows user launching Blender has writing permissions, so maybe there could be a conflict here ?
* Could you check that "C:\\USers\Admin" is not selected in the Edit -> Preferences -> File Paths -> Temporary files entry ?
You should be able to manually select a location in which you have permission if this value is set.
![image](https://user-images.githubusercontent.com/52042414/119697487-869c8d80-be50-11eb-8bea-d485de215d94.png)
* If none of the above works, you could extract the content of the .zip you downloaded, and modify the variable **SKETCHFAB_TEMP_DIR** in the file [addons/io_sketchfab_plugin/sketchfab/__init__.py (line 68)](https://github.com/sketchfab/blender-plugin/blob/master/addons/io_sketchfab_plugin/sketchfab/__init__.py#L68) with a value such as "C://Users/Hoang Trung/Desktop/NAMEOFYOURDIRECTORY", before rezipping the directory and re-installing the addon.

Hope this can help 🤞

**Comment by hgntrung** [comment]
Hello @loicSketchfab, 

Thanks for the response, really appreciate that. Yeah, you're right the problem is the Temporary files have the wrong path.  The issue is fixed yet.

Thank you very much, and have a good day.
