### ISSUE TITLE
Sketchfab New Format (.Binz)

### ISSUE THREAD

**Issue by yazancash** [sketchfab/blender-plugin#39]
Hello

Anyone noted that Sketchfab has changed model format into .Binz ?

Can someone update the script to support the new model format ?

fyi, Free version of Sketchfab-Ripper.com is still working fine. and it's based on similar Python script. maybe someone can read their script for updates.

thank you!

**Comment by PadreZippo** [comment]
Hello,

I'm not sure if you realize you are asking about Sketchfab ripping tools on an official Sketchfab repo.

Obviously we are not going to help fix or maintain illegal tools that can steal content from our users.
