### ISSUE TITLE
UV and Texture Messed Up

### ISSUE THREAD

**Issue by bpowel44** [sketchfab/blender-plugin#41]
Uploading to Sketchfab via blender is resulting in the image texture being projected incorrectly, see image. This problem didn't happen only a couple weeks ago. When I upload the same model directly to Sketchfab it works properly. Tried many different things to get it to work, applied transformation, packed all elements into blend file, made mesh manifold, lowered poly count to under 1 million. 

<img width="612" alt="Screen Shot 2021-06-24 at 4 47 37 PM" src="https://user-images.githubusercontent.com/60148320/123481137-8e229400-d5c0-11eb-9a71-d3c322077304.png">

**Comment by gorenje** [comment]
I also noticed this, I assumed it has something todo with Sketchfab since my plugin hasn't changed.

I worked around this by exporting to .glb format and then importing into Sketchfab - not optimal but works.

(Using 1.4.0 version of the plugin)

**Comment by bpowel44** [comment]
I got a response from Sketchfab today and they said they are addressing it and that they will push out a fix soon. Thank you for this awesome plug in :)
