### ISSUE TITLE
Unable to find some models

### ISSUE THREAD

**Issue by Biloot** [sketchfab/blender-plugin#49]
For example, this model : https://sketchfab.com/3d-models/le-redoutable-3185deedec374b1083dba6a9961e1878 is not available when I search for it with the plugin inside Blender (with the keyword "Redoutable" which works in the SketchFab website).
I do not understand why. With other models, importations are working and everything is OK.
I have the plugin version 1.4.1 and Blender 2.93.1 in Linux Mint 20.1.

**Comment by PadreZippo** [comment]
Hello,

That model is not available to download or purchase, so it will not appear in the plugin search.

To find available models, check out https://sketchfab.com/download
