### ISSUE TITLE
Riftz

### ISSUE THREAD

**Issue by Riftzie** [sketchfab/blender-plugin#50]
Hey there, I installed the Add-on and all but where the activate module is for the tab, there is no button to activate it.
![image](https://user-images.githubusercontent.com/91017960/133930151-be0b59ff-87fc-4e9d-9ffe-af8c93dc33c3.jpg)

**Comment by PadreZippo** [comment]
Hi there,

It looks like you might be using an outdated version. Can you make sure you're using 1.4.1?

What version of Blender are you running?

https://github.com/sketchfab/blender-plugin/releases/latest

**Comment by loicSketchfab** [comment]
Feel free to try the [latest update of the addon](https://github.com/sketchfab/blender-plugin/releases/latest) after having uninstalled the old version from your system. 
I'm closing this issue for now, but do not hesitate to reopen this issue if the bug still happens.
