### ISSUE TITLE
3.0

### ISSUE THREAD

**Issue by denpow** [sketchfab/blender-plugin#53]
Is the sketchfab blender plugin on 3.0?

**Comment by fire** [comment]
Tried in 3.0 and did not work.

**Comment by loicSketchfab** [comment]
Fixed with latest versions of the plugin, feel free to try out the version [1.5.0](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) of the addon which mainly targets Blender 3.0 and 3.1, but is compatible with Blender 2.83 to 3.2 (see release notes).
