### ISSUE TITLE
can't log in in blender, but logged in successfully in the web

### ISSUE THREAD

**Issue by Mingkon** [sketchfab/blender-plugin#54]
error message

HTTPSConnectionPool(host='sketchfab.com', port=443): Max retries exceeded with url: /oauth2/token/?grant_type=xxxxxxxxxxxxxxxx (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))

platform : win 10 pro
blender version: 2.93
sketchfab version: 1.41

**Comment by Mingkon** [comment]
<img width="166" alt="147ae5f5df6927113a90b1b4dbb4b96" src="https://user-images.githubusercontent.com/24671800/140100235-8966c662-38d4-40bf-956a-f9579360e744.png">

**Comment by dearyangyu** [comment]
close vpn...

**Comment by Mingkon** [comment]
closing VPN solves the problem
