### ISSUE TITLE
download doesnt work

### ISSUE THREAD

**Issue by adhhrg** [sketchfab/blender-plugin#56]
download doesnt work
<img width="753" alt="NcgWzof7yf" src="https://user-images.githubusercontent.com/63681591/141658058-ff914513-40b3-440d-ab48-abdcfa4dc448.png">

this is what happens after clicking download

**Comment by InfinityCg** [comment]
facing the same issue

blender version and build : 3.0 Beta | 7b530c609611
![image](https://user-images.githubusercontent.com/84709012/141683554-653ece03-9263-49cb-812b-842b1d53d4f7.png)

**Comment by loicSketchfab** [comment]
We've added an option to specify a custom download directory for such issues with the [release 1.5.0](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) of the addon. 

Previously the addon tried to create a directory in a Blender-generated temporary folder, which could potentially not be write-able
Selecting a folder as ["Download Directory"](https://github.com/sketchfab/blender-plugin#installation) in a directory you have access to should fix the issue, but feel free to reopen this ticket if it does not 👍
