### ISSUE TITLE
Error 13 when using plugin on Blender 3.0

### ISSUE THREAD

**Issue by JCatt** [sketchfab/blender-plugin#59]
Been getting Error 13, data not able to be processed since Blender updated to 3.0, even when I rollback to 2.93 I'm getting the same issue, even with 1.4.1

**Comment by melMass** [comment]
I think this repo is unmaintained. 
The active PR works fine for me:
https://github.com/sketchfab/blender-plugin/pull/52

**Comment by loicSketchfab** [comment]
Those errors have been fixed with the [release 1.5.0](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) of the addon indeed.
Please note that uploads from Blender 3.2 alphas will still produce an error 13 for now.
