### ISSUE TITLE
v1.4.2 not compatible with 2.83

### ISSUE THREAD

**Issue by schroef** [sketchfab/blender-plugin#61]
v1.4.2
bl2.83
OSX

I tried installing version 1.4.2 in blender 2.8 and 2.83, i get this error in return. Addon info states blender 2.80.0 though i just did noticed this note in the release page
```
Note: Tested for Blender 2.93.4, 2.93.5, 3.0.0 beta and 3.1.0 alpha.
```

```
xception in module register(): /Users/macpro1/Library/Application Support/Blender/2.83/scripts/addons/sketchfab-plugin-1-4-2/__init__.py
Traceback (most recent call last):
  File "/Applications/Blender-2.83/Blender.app/Contents/Resources/2.83/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/Users/macpro1/Library/Application Support/Blender/2.83/scripts/addons/sketchfab-plugin-1-4-2/__init__.py", line 1871, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "SketchfabBrowserProps" registration error: sort_by could not register
```

issue seems the enumProperty, however getting items used to work fine.
```
TypeError: EnumProperty(...): 'default' can't be set when 'items' is a function
```

**Comment by loicSketchfab** [comment]
Hi @schroef 👋 

The [release 1.5.0](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) of the addon should be compatible with Blender 2.83 (aside from an issue with rigged models explained in the releases notes).

If it does not work for you, could you please transfer us the errors you encounter again ? 
Those similar to your report should have been fixed, but feel free to reopen the issue if it does not 🤞
