### ISSUE TITLE
Problem on M1 Max Mac 

### ISSUE THREAD

**Issue by dynamico69** [sketchfab/blender-plugin#62]
I just can't get it to work on my Macbook Pro M1 Max - tried different Blender versions, eg. 2.93, 3.0 and 3.1 for Apple Silicon on each one I can install the plugin but don't get any content in the side panel.. when I install it on one of my older macs it works just fine... no idea what's wrong..

<img width="381" alt="Bildschirmfoto 2022-01-25 um 21 22 45" src="https://user-images.githubusercontent.com/44874427/151053627-1ac320f1-a58d-48b4-b214-23314ab9da5b.png">

**Comment by dynamico69** [comment]
No one interested ? :-(

**Comment by loicSketchfab** [comment]
Hey @dynamico69 

We've tested that the plugin worked on a Mac air M1 with the [release 1.5.0](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) of the addon.

Does it work for you after uninstalling the previous version of the addon ?

If not could you please transfer us:
* logs available in the System Console (when launched from a terminal in Mac or Linux, or available through Window->Toggle System Console on windows) 
* info on your system / blender version
* Maybe some screenshots of the error you encounter ?

Hope the version will work for you, but any feedback would be interesting if it does not.
