### ISSUE TITLE
Add support for downloding from a sketchfab website URL or model id.

### ISSUE THREAD

**Issue by gabrielmontagne** [sketchfab/blender-plugin#64]
Thanks for the addon, good stuff! 

The search on the website is still more comfortable than the search in the addon.  If I already know which model I need - because I found it on the site  -  I shouldn't need to try to reconstruct the search and navigate through pages and pages of models. 

Could there not be a "find model from URL" or perhaps from the URL id?

**Comment by loicSketchfab** [comment]
Hi @gabrielmontagne 👋 

We've added such a feature with the [release 1.5.0](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) of the addon, feel free to try it out, and re-open the issue if something does not work as expected.

Of course, check that the model url matches a downloadable model before importing it.
