### ISSUE TITLE
sketchfab not working in Mac M1

### ISSUE THREAD

**Issue by marliesilva** [sketchfab/blender-plugin#65]
there is a error report pops up when trying to download the sketchfab.onece you click the the box in the blender installer..the error pops up..anyone know what's the solution ??

**Comment by loicSketchfab** [comment]
Hi @marliesilva 👋 

We've tested that the plugin worked on a Mac M1 with the [release 1.5.0](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) of the addon.
Does it work for you after uninstalling the previous version of the addon ?
If not could you please transfer us:
* logs available in the System Console (when launched from a terminal in Mac or Linux, or available through Window->Toggle System Console on windows) 
* info on your system / blender version
* Maybe some screenshots of the error you encounter ?

Hope the version will work for you 🤞
