### ISSUE TITLE
Upload fails without warning when it exceeds allowed size.

### ISSUE THREAD

**Issue by chippwalters** [sketchfab/blender-plugin#69]
I was very confused recently as I was trying to upload a 300 plus megabyte model and it would not upload to my Pro account. But, then it would upload to my team account without issue. I couldn't figure out why that was until digging deeper and finally saw where it was failing due to it being too large for the Pro account. You should at least put something in the console to let people know.

**Comment by loicSketchfab** [comment]
Hey @chippwalters 👋 
We've just added a pop-up warning to take such cases into account upon upload.
You can check it in the [release 1.5.0](https://github.com/sketchfab/blender-plugin/releases/tag/1.5.0) of the addon.
Hope everything will work for you, but feel free to re-open this issue if something is still not right with this behaviour.

**Comment by chippwalters** [comment]
Thanks Loic for letting me know. Much appreciated.
