### ISSUE TITLE
View3D Tools Missing - Can't locate the Add On

### ISSUE THREAD

**Issue by TysonGersh** [sketchfab/blender-plugin#8]
Forgive me if I'm missing something obvious here, but I can't locate the installed addon. The instructions say it's located under "View3D --> Tools", but I can't find anything that says that in Blender 2.82. Can someone please clarify this? 

I had installed the previous version 1.1.0 and it just showed up below the toolbar in the 3D viewport, but it told me to update to the latest version, which apparently puts it in a different place? The location path appears to be the same, but as you can see in the images below they do not produce the same result when enabled. 

Here's w V 1.1.0
![image](https://user-images.githubusercontent.com/46682958/75980232-0b983180-5eb0-11ea-89be-245c77b1fa9a.png)

and here's w V 1.2.1
![image](https://user-images.githubusercontent.com/46682958/75980093-d5f34880-5eaf-11ea-864e-43ca44c4311c.png)

**Comment by PadreZippo** [comment]
Hi Tyson,

It's in the Sidebar view. By default, you can press the **N** key to toggle this, or go to **View → Sidebar**.

![image](https://user-images.githubusercontent.com/7097291/75999977-fed80580-5ed0-11ea-8480-a0a8f50adf96.png)

![image](https://user-images.githubusercontent.com/7097291/76000039-1a431080-5ed1-11ea-9fe8-d736f8e7c217.png)

**Comment by TysonGersh** [comment]
Awesome, thanks so much @PadreZippo (James)!
